get:
  summary: Получить список всех товаров
  operationId: getAllProducts
  responses:
    '200':
      description: Успешный ответ
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas.yaml#/ProductDTO'
