openapi: 3.0.3
info:
  title: Online Store API
  description: Спецификация API для онлайн-магазина
  version: 1.0.0

servers:
  - url: https://api.yourstore.com
    description: Production server

paths:
  /products:
    $ref: './paths/products.yaml'
  /orders:
    $ref: './paths/orders.yaml#/orders'
  /orders/{id}:
    $ref: './paths/orders.yaml#/orderById'

components:
  schemas:
    ProductDTO:
      $ref: './components/schemas.yaml#/ProductDTO'
    OrderDTO:
      $ref: './components/schemas.yaml#/OrderDTO'